# Generated by Django 3.0.14 on 2023-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.DateField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('insight', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dash_board_data',
            },
        ),
    ]
