# Generated by Django 3.0.14 on 2023-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230609_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='data_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
